config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pictures#index'
  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :descending_order, -> { order("created_at DESC") }
	scope :newest_five, -> { descending_order.limit(5) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@pictures = Picture.newest_five
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.create(picture_params)
		redirect_to root_path
	end
	def show
		@picture = Picture.find(params[:id])
	end

	def destroy
		@picture = Picture.find(params[:id])
		Picture.destroy(@picture)
		redirect_to root_path
	end
	def edit
		@picture = Picture.find(params[:id])
	end
	def update
		@picture = Picture.find(params[:id])
		@picture.update_attributes(picture_params)
		redirect_to root_path
	end
	
	private

	def picture_params
		params.require(:picture).permit(:title, :caption, :url)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_header.html.erb
<h1 class="pull-left"><%= link_to "Picture App", root_path %></h1>

<div class="pull-right">
	<% if user_signed_in? %>
		<h3><%= link_to "New Picture", new_picture_path%> | <%= link_to "Log Out", destroy_user_session_path, :method => :delete  %></h3>	
	<% else %>
	<h3><%= link_to "Sign Up", new_user_registration_path %> | <%= link_to "Sign In", new_user_session_path %></h3>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PictureTime</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<div class="container">
			<%= render "layouts/header" %>
		</div>
	</header>
	
		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
		<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<%= form_for @picture do |f| %>
	
	<p><%= f.label :title %>
	<%= f.text_field :title %></p>

	<p><%= f.label :caption %>
	<%= f.text_field :caption %></p>

	<p><%= f.label :url %>
	<%= f.text_field :url %></p>

	<%= submit_tag("Submit"), :class => 'alert'  %>
<% end %>

app/views/pictures/index.html.erb
<% @pictures.each do |picture| %>
			<%= link_to picture_url(picture.id) do %><div class="image_card" style="background-image: url(<%= picture.url %>)"><h2><%= picture.title %></h2></div>
			<% end %>	
<% end %>

app/views/pictures/new.html.erb
<%= link_to "Back", root_path, class: "pull-left"  %>
<h1>Add a Pic</h1>

<%= form_for @picture do |f| %>

	<p><%= f.label :title %><%= f.text_field :title %></p>
	<p><%= f.label :caption %><%= f.text_field :caption %></p>
	<p><%= f.label :url %><%= f.text_field :url %></p>
	<%= f.submit 'Submit', :class => 'alert' %>
<% end %>

app/views/pictures/show.html.erb
<%= link_to "Back", root_path  %>
<%= @picture.title  %>
<%= @picture.caption %>
<img src="<%= @picture.url %>"> 